package net.llvg.eventlib;

/**
 * Base type of event listener generated by {@link ListenerFactory}
 *
 * @see ListenerFactory ListenerFactory
 */
public interface UncheckedListener {
    /**
     * Invoke the listener with the {@code event}.
     *
     * @param event The object being used.
     */
    void invoke(Object event);
}
